### ISSUE TITLE
Fix server crashing on authenticated requests

### ISSUE THREAD

**Issue by jackcmeyer** [hammer-io/endor#30]
As a user, I would like the server to not crash on an authenticated request. 

The leading theory right now is that express-sessions should not be used in production (see the documentation here: https://www.npmjs.com/package/express-session). 

Look here for compatible session stores: https://github.com/expressjs/session#compatible-session-stores

**Comment by jackcmeyer** [comment]
@KrashLeviathan could you provide any updates as you find them here?

**Comment by KrashLeviathan** [comment]
Fixed by #31
