### ISSUE TITLE
Deploy to Server

### ISSUE THREAD

**Issue by clarkerican** [hammer-io/endor#6]
Consider packaging in docker container and setting up the deploy pipeline through Travis.

**Comment by KrashLeviathan** [comment]
The VM has the following domain aliases: `hammer-io-test.ece.iastate.edu` and `api-hammer-io-test.ece.iastate.edu`. To deploy our applications via docker and serve each app dependent upon the domain used, follow [this tutorial](https://tech.mybuilder.com/virtual-hosts-with-docker/) which uses a docker-gen + Nginx reverse proxy to accomplish what we want.

**Comment by jackcmeyer** [comment]
We will need to do this in #hammer-io/koma#4 as well

**Comment by jackcmeyer** [comment]
@KrashLeviathan we should also configure the app to do the following: 
- [ ] In the index.js file, configure the loggers to log to a file.

**Comment by KrashLeviathan** [comment]
Make another issue for those other ones.
