### ISSUE TITLE
Create get project description endpoint

### ISSUE THREAD

**Issue by NathanDeGraaf** [hammer-io/endor#66]
Similar to the /projects/:projectId/issues endpoint, I would like to be able to get the description (readme.md) for a project to be displayed on the project description page. (the front end is statically displaying tyr's description right now)

**Comment by jackcmeyer** [comment]
Added a field to the `projects/:id` endoint called `markdownDescription` which contains the README contents from the user's github repo or generate markdown from project name + project description
