### ISSUE TITLE
Update the url to accept/decline an invite

### ISSUE THREAD

**Issue by clarkerican** [hammer-io/endor#8]
The url defined in the EmailService that's sent to the user to click on doesn't currently point to anything useful because the UI hasn't been developed yet. Once the UI has a route for user invite management, this url needs to be updated to point to that route.

**Comment by KrashLeviathan** [comment]
Additional requirements migrated from hammer-io/yggdrasil#106

When the user receives an email inviting them to a project, the link at the bottom should take them to the email notification settings page in the web application. There's currently an "Unsubscribe" button on the email template as well, but that can probably be removed, as everything will be handled through the Email Notification Settings page.

- Update the email template `endor/zurb-email-templates/invite.html`.
- View the `endor/zurb-email-templates/README.md` for instructions on generating the actual html that will be used.
- Generate the html and add it to `invite.email.js`
